### ISSUE TITLE
Don't use singleton

### ISSUE THREAD

**Issue by Flamefire** [MKlimenko/embed#1]
You implement (parts of) the singleton pattern. But your whole class is static except for your convenience function call operator.
So there is not need in making the class a singleton at all. Just remove the private ctors and the singleton method and simply create a default constructed global instance `embed`

Why I found this: You return a reference from your singleton method but store an instance of it in the global variable. So you make a copy. Looking further I found that the whole singleton pattern makes no sense here.

**Comment by MKlimenko** [comment]
You are totally correct, it was a last-minute call, I kinda overengineered this bit.

Thanks for your attention!
